version: "3"

services:
  api-server:
    build:
      context: .
    container_name: api-server
    image: api-server
    depends_on:
      - "mysql"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=secret
    volumes:
      - ./logs:/logs
    networks:
      - app-network
    ports:
      - "3000:3000"

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql


networks:
  app-network:
    driver: bridge
